server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #bootstrap: true
          uri: file:///D:/workspace/intellij_springboot/msa_ecomms_configs/
            #uri: https://github.com/hwan2272/spring-cloud-config
          #bootstrap: false

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh