server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: file:///D:/workspace/intellij_springboot/msa_ecomms_configs
        git:
          uri: https://github.com/hwan2272/msa_ecomms_configs
          #bootstrap: true
          #bootstrap: false

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh